### ISSUE TITLE
db json?

### ISSUE THREAD

**Issue by Zopenzop** [KaikyuLotus/dart-mongo-lite#4]
`var db = Database('resources/db');`
What exactly is db, is it a json file? If yes, what should be the format of the json file? What needs to be filled in there?
Does this package also work for mongo cloud databases? I do have a connection string for the same but not using local databases.

**Comment by KaikyuLotus** [comment]
Hi,

this package is a "fake" version of MongoDB, which works with a simple JSON file and is suggested only for small quantities of data.
The JSON can be empty (containing at least {}) or non-existent.

Since it's not real MongoDB you can't connect to cloud databases and doesn't support the majority of MongoDB functions.

**Comment by Zopenzop** [comment]
I'll try to make use of alternatives. Thanks for the information.
